#!/bin/sh

# Absolute path to this script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Load husky functions
. "${SCRIPT_DIR}/_/husky.sh"

# Run lint-staged
npx lint-staged || {
  echo "lint-staged failed"
  exit 1
}
